---
apiVersion: v1
kind: Secret
metadata:
  namespace: azure
  name: vsts
type: Opaque
stringData:
  azpUrl: {{url}}
  azpToken: {{token}}
  azpPool: {{name}}

---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: azure
  name: vsts-agent
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: vsts-agent
    spec:
      containers:
      - name: vsts-agent
        image: pvizeli/azure-agent:1.0-armv7
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: vsts
                key: azpUrl
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: vsts
                key: azpToken
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: vsts
                key: azpPool
        volumeMounts:
        - mountPath: /run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /run/docker.sock